// Bilingual word bank. Every entry has an English and Spanish word, and a
// difficulty tier matching a rough age range. Kept in its own file so it's
// trivial to extend later without touching game logic.
window.WORD_BANK = [
  // tier: "kids" -- simple, concrete, easy to draw
  { en: "Dog", es: "Perro", tier: "kids" },
  { en: "Cat", es: "Gato", tier: "kids" },
  { en: "Sun", es: "Sol", tier: "kids" },
  { en: "Tree", es: "Árbol", tier: "kids" },
  { en: "House", es: "Casa", tier: "kids" },
  { en: "Ball", es: "Pelota", tier: "kids" },
  { en: "Fish", es: "Pez", tier: "kids" },
  { en: "Bird", es: "Pájaro", tier: "kids" },
  { en: "Car", es: "Carro", tier: "kids" },
  { en: "Star", es: "Estrella", tier: "kids" },
  { en: "Flower", es: "Flor", tier: "kids" },
  { en: "Moon", es: "Luna", tier: "kids" },
  { en: "Apple", es: "Manzana", tier: "kids" },
  { en: "Banana", es: "Plátano", tier: "kids" },
  { en: "Hat", es: "Sombrero", tier: "kids" },
  { en: "Shoe", es: "Zapato", tier: "kids" },
  { en: "Cake", es: "Pastel", tier: "kids" },
  { en: "Boat", es: "Barco", tier: "kids" },
  { en: "Cloud", es: "Nube", tier: "kids" },
  { en: "Rain", es: "Lluvia", tier: "kids" },
  { en: "Egg", es: "Huevo", tier: "kids" },
  { en: "Cow", es: "Vaca", tier: "kids" },
  { en: "Pig", es: "Cerdo", tier: "kids" },
  { en: "Duck", es: "Pato", tier: "kids" },
  { en: "Frog", es: "Rana", tier: "kids" },
  { en: "Book", es: "Libro", tier: "kids" },
  { en: "Chair", es: "Silla", tier: "kids" },
  { en: "Table", es: "Mesa", tier: "kids" },
  { en: "Door", es: "Puerta", tier: "kids" },
  { en: "Window", es: "Ventana", tier: "kids" },

  // tier: "family" -- everyday objects/actions, a bit more specific
  { en: "Bicycle", es: "Bicicleta", tier: "family" },
  { en: "Airplane", es: "Avión", tier: "family" },
  { en: "Umbrella", es: "Sombrilla", tier: "family" },
  { en: "Guitar", es: "Guitarra", tier: "family" },
  { en: "Pizza", es: "Pizza", tier: "family" },
  { en: "Birthday party", es: "Fiesta de cumpleaños", tier: "family" },
  { en: "Swimming pool", es: "Piscina", tier: "family" },
  { en: "Snowman", es: "Muñeco de nieve", tier: "family" },
  { en: "Volcano", es: "Volcán", tier: "family" },
  { en: "Spaceship", es: "Nave espacial", tier: "family" },
  { en: "Lighthouse", es: "Faro", tier: "family" },
  { en: "Waterfall", es: "Cascada", tier: "family" },
  { en: "Backpack", es: "Mochila", tier: "family" },
  { en: "Skateboard", es: "Patineta", tier: "family" },
  { en: "Camera", es: "Cámara", tier: "family" },
  { en: "Robot", es: "Robot", tier: "family" },
  { en: "Dinosaur", es: "Dinosaurio", tier: "family" },
  { en: "Castle", es: "Castillo", tier: "family" },
  { en: "Pirate", es: "Pirata", tier: "family" },
  { en: "Superhero", es: "Superhéroe", tier: "family" },
  { en: "Campfire", es: "Fogata", tier: "family" },
  { en: "Soccer goal", es: "Portería de fútbol", tier: "family" },
  { en: "Ice cream cone", es: "Cono de helado", tier: "family" },
  { en: "Rainbow", es: "Arcoíris", tier: "family" },
  { en: "Treasure chest", es: "Cofre del tesoro", tier: "family" },
  { en: "Snorkeling", es: "Buceo con tubo", tier: "family" },
  { en: "Fire truck", es: "Camión de bomberos", tier: "family" },
  { en: "Roller coaster", es: "Montaña rusa", tier: "family" },
  { en: "Farmer", es: "Granjero", tier: "family" },
  { en: "Astronaut", es: "Astronauta", tier: "family" },

  // tier: "adults" -- abstract concepts, idioms, harder to mime/draw
  { en: "Procrastination", es: "Procrastinación", tier: "adults" },
  { en: "Jealousy", es: "Celos", tier: "adults" },
  { en: "Negotiation", es: "Negociación", tier: "adults" },
  { en: "Bureaucracy", es: "Burocracia", tier: "adults" },
  { en: "Nostalgia", es: "Nostalgia", tier: "adults" },
  { en: "Inflation", es: "Inflación", tier: "adults" },
  { en: "Stock market", es: "Bolsa de valores", tier: "adults" },
  { en: "Job interview", es: "Entrevista de trabajo", tier: "adults" },
  { en: "Mortgage", es: "Hipoteca", tier: "adults" },
  { en: "Retirement", es: "Jubilación", tier: "adults" },
  { en: "Democracy", es: "Democracia", tier: "adults" },
  { en: "Time travel", es: "Viaje en el tiempo", tier: "adults" },
  { en: "Artificial intelligence", es: "Inteligencia artificial", tier: "adults" },
  { en: "Midlife crisis", es: "Crisis de la mediana edad", tier: "adults" },
  { en: "Conspiracy theory", es: "Teoría de la conspiración", tier: "adults" },
  { en: "Long-distance relationship", es: "Relación a distancia", tier: "adults" },
  { en: "Writer's block", es: "Bloqueo del escritor", tier: "adults" },
  { en: "Deja vu", es: "Deja vu", tier: "adults" },
  { en: "Sarcasm", es: "Sarcasmo", tier: "adults" },
  { en: "Compound interest", es: "Interés compuesto", tier: "adults" },
];
